### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by laughmaker** [nshintio/uicollectionview-reordering#5]
Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2015-09-19 15:18:24.524 Example[32028:1966216] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2015-09-19 15:18:25.002 Example[32028:1966216] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2015-09-19 15:18:25.755 Example[32028:1966216] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2015-09-19 15:18:26.843 Example[32028:1966216] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2015-09-19 15:18:28.773 Example[32028:1966216] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[**NSArrayM objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 100]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00000001092c1f65 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010b178deb objc_exception_throw + 48
    2   CoreFoundation                      0x00000001091a5a94 -[__NSArrayM objectAtIndex:] + 212
    3   Example                             0x00000001090b6b3c _TFC7Example32CHTCollectionViewWaterfallLayout34layoutAttributesForItemAtIndexPathfS0_FCSo11NSIndexPathGSqCSo32UICollectionViewLayoutAttributes_ + 748
    4   Example                             0x00000001090b6cba _TToFC7Example32CHTCollectionViewWaterfallLayout34layoutAttributesForItemAtIndexPathfS0_FCSo11NSIndexPathGSqCSo32UICollectionViewLayoutAttributes_ + 58
    5   UIKit                               0x000000010a562cf0 -[UICollectionViewData layoutAttributesForItemAtIndexPath:] + 315
    6   UIKit                               0x000000010a51a1ae -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 351
    7   UIKit                               0x000000010a51ab6f -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 169
    8   Example                             0x00000001090bcc48 _TFC7Example19ThirdViewController14collectionViewfS0_FTCSo16UICollectionView22cellForItemAtIndexPathCSo11NSIndexPath_CSo20UICollectionViewCell + 120
    9   Example                             0x00000001090bcf2f _TToFC7Example19ThirdViewController14collectionViewfS0_FTCSo16UICollectionView22cellForItemAtIndexPathCSo11NSIndexPath_CSo20UICollectionViewCell + 79
    10  UIKit                               0x000000010a50acf1 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:] + 481
    11  UIKit                               0x000000010a50d10c -[UICollectionView _updateVisibleCellsNow:] + 4242
    12  UIKit                               0x000000010a511871 -[UICollectionView layoutSubviews] + 247
    13  UIKit                               0x0000000109db211c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 710
    14  QuartzCore                          0x000000010ecb936a -[CALayer layoutSublayers] + 146
    15  QuartzCore                          0x000000010ecadbd0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    16  UIKit                               0x0000000109da1d7b -[UIView(Hierarchy) layoutBelowIfNeeded] + 1083
    17  UIKit                               0x000000010a526b90 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 241
    18  UIKit                               0x000000010a52d42b -[UICollectionView _updateReorderingTargetPosition:forced:] + 1181
    19  UIKit                               0x000000010a52e51f -[UICollectionView _autoscrollForReordering:] + 2760
    20  Foundation                          0x00000001098cb671 __NSFireTimer + 83
    21  CoreFoundation                      0x0000000109222364 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 20
    22  CoreFoundation                      0x0000000109221f11 __CFRunLoopDoTimer + 1089
    23  CoreFoundation                      0x00000001091e38b1 __CFRunLoopRun + 1937
    24  CoreFoundation                      0x00000001091e2e98 CFRunLoopRunSpecific + 488
    25  GraphicsServices                    0x000000010e76ead2 GSEventRunModal + 161
    26  UIKit                               0x0000000109d01676 UIApplicationMain + 171
    27  Example                             0x00000001090beead main + 109
    28  libdyld.dylib                       0x000000010bc9092d start + 1
    29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by rakaramos** [comment]
Please, could you give more information? Just the stacktrace isn't helping here.
I've just tested it in XCode 7 and it's working fine... What did you do to make it crash?
