### ISSUE TITLE
UICollectionview-reordering feature before iOS 9.0

### ISSUE THREAD

**Issue by Minakshi-bawa** [nshintio/uicollectionview-reordering#8]
How can we implement collection view - reordering feature for iOS 8.0 too ?

**Comment by verma-manish58** [comment]
I guess we need to change in the datasource and then reload the collection view as there is no easy solution provided by Apple.

**Comment by Soniya-Iphonedev** [comment]
I tried with Objective -C but it is not working at all though the gesture is called correctly.

Here is my complete sample code :

#import "ViewController.h"
#import "CollectionViewCell.h"

@interface ViewController ()
{
    NSMutableArray *arrItems;
    UILongPressGestureRecognizer *longPressGesture;
    __weak IBOutlet UICollectionView *collection;
}
@end

@implementation ViewController
- (void)viewDidLoad {
  [super viewDidLoad];
  arrItems=[[NSMutableArray alloc]init];
  for (int i = 1; i<=30; i++) {
      [arrItems addObject:[NSString stringWithFormat:@"%d",i]];
  }
  longPressGesture = [[UILongPressGestureRecognizer alloc]initWithTarget:self action:@selector(handleLongGesture:)];
  [collection addGestureRecognizer:longPressGesture];
  // Do any additional setup after loading the view, typically from a nib.
  }
- (void)didReceiveMemoryWarning {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
  }

-(void)handleLongGesture:(UILongPressGestureRecognizer *)gesture{
     CGPoint location = [gesture locationInView:collection];
    switch(gesture.state){
        case UIGestureRecognizerStateBegan:{
            NSIndexPath *selectedIndexPath = [collection indexPathForItemAtPoint:location];
            NSLog(@"Selected : %ld",(long)selectedIndexPath.row);
            if (selectedIndexPath!=nil) {
                [collection beginInteractiveMovementForItemAtIndexPath:selectedIndexPath];
            }
        }
            break;
            case UIGestureRecognizerStateChanged:
            [collection updateInteractiveMovementTargetPosition:location];
    break;
            case UIGestureRecognizerStateEnded:
            [collection endInteractiveMovement];
            break;
            default:
            [collection cancelInteractiveMovement];
    }
}
#pragma mark - UICollectionViewDataSource
- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section {
  return arrItems.count;
  }
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath {
  static NSString \* cellIdentifier = @"CollectionViewCell";
  
  CollectionViewCell \* cell = [collectionView dequeueReusableCellWithReuseIdentifier:cellIdentifier forIndexPath:indexPath];
    cell.lblRow.text =  [arrItems objectAtIndex:indexPath.row];
  return cell;
  }
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath{
  }
- (void)moveItemAtIndexPath:(NSIndexPath *)indexPath toIndexPath:(NSIndexPath *)newIndexPath{
  NSLog(@"Entered");
  NSString *temp = [arrItems objectAtIndex:indexPath.item];
  [arrItems removeObjectAtIndex:indexPath.item];
  [arrItems insertObject:temp atIndex:newIndexPath.item];
  temp=nil;
  }

**Comment by mmatoszko** [comment]
@Minakshi-bawa it looks like it's an iOS 9 feature.
Anyway I'm a _**little**_ late to respond here..
Hope everyone already updated their deployment targets and we can close this issue 🎉
