### ISSUE TITLE
Dragging a cell out of sight of its last proposed indexpath, dropping it -> the cell will not be cleaned up

### ISSUE THREAD

**Issue by ghost** [nshintio/uicollectionview-reordering#9]
iOS has a bug where the dragged cells were left wherever they got dropped and never cleaned up. I created an example based on this project:
[UICollectionViewReorderingBug.mov.zip](https://github.com/nshintio/uicollectionview-reordering/files/86029/UICollectionViewReorderingBug.mov.zip)
Has anyone an idea how to workaround it?

**Comment by thy3331** [comment]
Same issue, drag item at the edge of screen,an slide view,then item can be place almost anywhere on screen. might due to items' reusing?

**Comment by ghost** [comment]
Possible. According to Apple, the bug is fixed - when you can still reproduce it in iOS 9.3, you should file another bug at Apples bugreporter.

**Comment by thy3331** [comment]
Seems you need to using collectionView to call method -setNeedsDisplay, i've called this method after exchange items,and seems that this issue is fixed.

here's my code

`-(void)collectionView: moveItemAtIndexPath{

```
<# HERE IS WHAT YOU WANT TO DO#>   


dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.25 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    [self.busLineView reloadData];// <-i'm using model for source ,so i need to reload data here
    [self.busLineView setNeedsDisplay];// <- HERE, i'm called this and this issue is fixed[just for me now]
});
```

}
`

UPDATE

Alright = =,i'm too simple..this issue still can be triggered;

**Comment by ghost** [comment]
Thanks for that hint! I think i can close that issue by now 👍

**Comment by thy3331** [comment]
alright.. eh.the floating view is actually a UIView,so.i'm removing all subviews and reloading data,and. it's fixed again = =...  hoping this time is really fixed..
